version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFixesProject
  gitServerName: pooja
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.testfixes.integrations:f1
  packages:
  - name: TestFixesProject
    version: "1.0"
- serviceName: pub.smime:processSignedData
  packages:
  - name: WmPublic
    version: 12.1.0.0.1202
- serviceName: pub.date:compareDates
  packages:
  - name: WmPublic
    version: 12.1.0.0.1202
